trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

jobs:
- template: templates/build.test.and.benchmark.yaml
  parameters:
    vmImage: 'ubuntu-latest'
    solution_to_build: $(Endjin_Solution_To_Build)
    benchmarkProjectName: 'TestBenchmark.Benchmark'
