parameters:
  postTestSteps: []
  vmImage: ''
  solution_to_build: ''

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    BuildConfiguration: 'Release'
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    SolutionToBuild: ${{ parameters.solution_to_build }}

  steps:

  - task: DotNetCoreCLI@2
    displayName: 'Restore & Build'
    inputs:
      command: 'build'
      projects: $(SolutionToBuild)
      arguments: '--configuration $(BuildConfiguration)'
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    displayName: 'Run Executable Specifications'
    inputs:
      command: 'test'
      projects: $(SolutionToBuild)
      arguments: '-c $(BuildConfiguration) --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      nobuild: true
  
  - ${{ parameters.postTestSteps }}